version: '3.4'

services:
  nodejsrevisit:
    image: nodejsrevisit:1.2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
